/**
 * Major Pakistani cities, offered as suggestions when a clinic adds a location.
 *
 * Suggestions, not a closed list: a clinic in a town that is not here must
 * still be able to type its own, so the field stays free text underneath. The
 * point is spelling consistency — coverage is resolved by matching the city on
 * a location against the city on a coverage row, and "Karachi" vs "karachi "
 * vs "Karachy" silently breaks that match.
 *
 * Ordered by population, so the ones a clinic is most likely to want come first
 * before any filtering is applied.
 */
export const MAJOR_PAKISTANI_CITIES = [
  'Karachi',
  'Lahore',
  'Faisalabad',
  'Rawalpindi',
  'Gujranwala',
  'Peshawar',
  'Multan',
  'Hyderabad',
  'Islamabad',
  'Quetta',
  'Bahawalpur',
  'Sargodha',
  'Sialkot',
  'Sukkur',
  'Larkana',
  'Sheikhupura',
  'Rahim Yar Khan',
  'Jhang',
  'Dera Ghazi Khan',
  'Gujrat',
  'Sahiwal',
  'Wah Cantonment',
  'Mardan',
  'Kasur',
  'Okara',
  'Mingora',
  'Nawabshah',
  'Chiniot',
  'Kotri',
  'Kamoke',
  'Hafizabad',
  'Sadiqabad',
  'Mirpur Khas',
  'Burewala',
  'Kohat',
  'Khanewal',
  'Dera Ismail Khan',
  'Turbat',
  'Muzaffargarh',
  'Abbottabad',
  'Mandi Bahauddin',
  'Shikarpur',
  'Jacobabad',
  'Jhelum',
  'Khanpur',
  'Khairpur',
  'Khuzdar',
  'Pakpattan',
  'Hub',
  'Daska',
  'Gojra',
  'Muridke',
  'Bahawalnagar',
  'Samundri',
  'Tando Allahyar',
  'Attock',
  'Vehari',
  'Kot Addu',
  'Wazirabad',
  'Mansehra',
  'Layyah',
  'Swabi',
  'Chishtian',
  'Charsadda',
  'Kandhkot',
  'Nowshera',
  'Bhakkar',
  'Gwadar',
  'Mirpur',
  'Muzaffarabad',
  'Gilgit',
  'Skardu',
] as const;
